### ISSUE TITLE
Add to pypi

### ISSUE THREAD

**Issue by be4zad** [mrgick/duckduckgo-chat-ai#6]

**Comment by mrgick** [comment]
Hello, I released https://pypi.org/project/duck-chat/
1. Install
```
pip install -U duck-chat
```
2. Run cli
```
duck_chat
```

**Comment by mrgick** [comment]
Someday I'll update the readme to describe all the features =)

Have a nice day

**Comment by be4zad** [comment]
Thank you❤️
